#name: workflow.yml

# 工作流名称：在 GitHub Actions 中显示为 "publish"
# 说明：这是该 CI/CD 工作流的名称，会在 GitHub 的 Actions 标签页中显示。
name: "publish"

# 触发条件：当向名为 'release' 的分支推送代码时触发此工作流
# 此工作流不会在 main 或其他分支触发。只有当你将代码推送到 release 分支时，才会自动执行构建和发布。推荐用于“预发布”或“正式发布”流程，避免频繁发布。
on:
  push:
    branches:
      - release

# 这是发布带签名证书的通用 macOS 应用的示例。
# 每次推送到 `release` 分支时，它会创建或更新一个 GitHub Release，
# 构建你的应用，并将构建产物（artifacts）上传到该 Release。
jobs:
  publish-tauri:
    # 给予此 Job 操作仓库内容的写权限（用于创建/更新 GitHub Release）
    permissions:
      contents: write
    # 构建策略配置
    strategy:
      # 即使某个任务失败，也继续运行其他任务（这里只有一个任务，作用不大）。
      fail-fast: false
      # 手动定义构建任务矩阵。
      matrix:
        include:
          # 配置构建矩阵：仅包含一个目标 —— Universal macOS（支持 arm64 和 x86_64）
          - platform: 'macos-latest'      # 使用最新的 macOS 虚拟机（GitHub Hosted Runner）。
            # 告诉 cargo tauri build 构建 通用二进制（Universal），即同时支持 Apple Silicon（M1/M2）和 Intel Mac。
            args: '--target universal-apple-darwin'
    # 指定运行此 Job 的虚拟机环境（从 matrix 中动态获取）
    runs-on: ${{ matrix.platform }}
    # 构建步骤列表
    steps:
      # 第一步：检出代码仓库（包括子模块）
      # 使用 GitHub 官方的 checkout 动作，将代码拉取到 CI 环境中。
      # 默认会递归检出子模块（Tauri 有时依赖 git 子模块）。
      - uses: actions/checkout@v4
      # # 第二步：设置 Node.js 环境
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*     # 安装最新的 LTS 版本 Node.js
      # 第三步：安装 Rust 稳定版工具链
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # 为 macOS 平台安装两个目标架构的交叉编译支持
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      # 第四步：安装前端依赖
      - name: install frontend dependencies
        run: yarn install     # 根据您使用的选项，将其更改为 npm、pnpm 或 bun。
      # 第五步：导入 Apple 开发者证书（用于代码签名）
      - name: import Apple Developer Certificate
        # 防止钥匙串自动锁定 3600 秒。
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          security find-identity -v -p codesigning build.keychain
      # 第六步：验证证书是否正确导入，并提取签名身份（Identity）
      - name: verify certificate
        run: |
          CERT_INFO=$(security find-identity -v -p codesigning build.keychain | grep "Developer ID Application")
          CERT_ID=$(echo "$CERT_INFO" | awk -F'"' '{print $2}')
          echo "CERT_ID=$CERT_ID" >> $GITHUB_ENV
          echo "Certificate imported."
      # 第七步：使用 Tauri Action 构建、签名并发布应用
      - name: build and publish
        uses: tauri-apps/tauri-action@v0
        env:
          # GitHub Token（自动提供）
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Apple ID 登录信息（用于连接 App Store Connect，非必须）
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # 证书信息（再次传递，确保安全）
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          # 从上一步获取的签名身份
          APPLE_SIGNING_IDENTITY: ${{ env.CERT_ID }}
        with:
          #  发布的标签名：格式为 app-v1.0.0（自动替换 __VERSION__ 为 package.json 中的版本）
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          # Release 显示名称
          releaseName: "App v__VERSION__"
          # Release 描述内容
          releaseBody: "See the assets to download this version and install."
          # 是否为草稿（建议设为 true，人工确认后再发布）
          releaseDraft: true
          # 是否为预发布版本
          prerelease: false
          # 构建参数（从 matrix 中传入）
          args: ${{ matrix.args }}